spring:
  application:
    name: ChatBot
  ai:
    openai:
      chat:
        options:
          model: gpt-3.5-turbo
  data:
    mongodb:
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id:

chatbot:
  geo:
    url: https://api.openweathermap.org/data/2.5/weather
    api_key: ${Weather_API}
    locations:
      - lat: 29.5581
        lng: 34.9482
        name: Eilat
      - lat: 32.0853
        lng: 34.7818
        name: Tel Aviv
      - lat: 33.2783
        lng: 35.5796
        name: Metula

app:
  schedule:
    reload-interval: 600000
#logging:
#  level:
#    root: debug
