spring:
  application:
    name: ChatBot

  ai:
    openai:
      chat:
        options:
          model: gpt-3.5-turbo

chatbot:
  geo:
    url: https://api.openweathermap.org/data/2.5/weather
    api_key: ${Weather_API}
    locations:
      - lat: 29.5581
        lng: 34.9482
        name: Eilat
      - lat: 32.0853
        lng: 34.7818
        name: Tel Aviv
      - lat: 33.2783
        lng: 35.5796
        name: Metula

app:
  schedule:
    reload-interval: 600000
  jwt:
    jwtSecret: mySecret123!
    jwtExpirationMs: 60000000000000000
